### ISSUE TITLE
SIP Creator - user can not delete uploaded files

### ISSUE THREAD

**Issue by PhillipTommerholt** [eark-project/earkweb#37]
If an user by mistake uploads a wrong file, the whole SIP creation process has to be deleted since the user does not have the possibility to delete a selected file.
![udklip](https://cloud.githubusercontent.com/assets/15984159/17620709/79e0de54-608e-11e6-9c65-2b3f45aed43c.PNG)

**Comment by janrn** [comment]
Hi Phillip, this is not implemented because the actual SIP creation module with options to manipulate files is supposed to come from Magenta.

**Workaround**: When you select files for an SIP, they are moved to the working area, and you can manually delete them from there. Select the package, go to representations/default/data and delete the file. Refresh the SIP Creator page by hitting F5 and you should be good to go.

**Comment by PhillipTommerholt** [comment]
Thanks for info!

**Comment by shsdev** [comment]
It would be easy to add this functionality to the working area. Let me know if there is still need to do this from the web interface or if you are fine doing it in the working area folder directly.

**Comment by shsdev** [comment]
Deleting uploaded files is now possible.
