### ISSUE TITLE
Confusing and security sensitive error output by upload error message

### ISSUE THREAD

**Issue by rgraf** [eark-project/earkweb#58]
The error message in response of the unexpected file upload e.g. (localhost:8000/earkweb/submission/upload_step4/97) additionally otputs a lot of security relevant information about login with user name, csrftoken, sessionid and different configuration settings.

**Comment by shsdev** [comment]
The error message contains details because the docker-compose deployment starts the application in debug mode. This is acceptable as the docker-compose setup is only for testing purposes. This is controlled in the settings.py with the "DEBUG = True" setting which should be turned off in production. However, production deployment should be done using WSGI, Kubernetes, etc.

**Comment by shsdev** [comment]
Deployment for production is using WSGI and Supvervisord
